#!/usr/bin/env bash

# 🎡 QUICK START - Sistema de Reservas de Parque Temático

echo "🎡 Sistema de Reservas de Parque Temático"
echo "=========================================="
echo ""
echo "⚡ INÍCIO RÁPIDO (3 PASSOS)"
echo ""
echo "Passo 1: Instale as dependências"
echo "  $ ./setup.sh"
echo "  (ou instale manualmente: see Setup Manual below)"
echo ""
echo "Passo 2: Abra 2 terminais e execute:"
echo ""
echo "  Terminal 1 - API Backend:"
echo "    $ cd api"
echo "    $ ruby app.rb"
echo "    ✅ API rodando em http://localhost:4567"
echo ""
echo "  Terminal 2 - Frontend:"
echo "    $ cd frontend" 
echo "    $ npm run dev"
echo "    ✅ Frontend rodando em http://localhost:3000"
echo ""
echo "Passo 3: Abra o navegador"
echo "  http://localhost:3000"
echo ""
echo "=========================================="
echo ""
echo "🎯 TESTES RÁPIDOS"
echo ""
echo "1️⃣  Visitante (Login):"
echo "   - Menu Principal → Portal do Visitante"
echo "   - Digite ID: 1"
echo "   - Faça uma reserva!"
echo ""
echo "2️⃣  Admin (Gerenciamento):"
echo "   - Menu Principal → Menu Administrador"
echo "   - Veja atrações, visitantes, filas e estatísticas"
echo ""
echo "3️⃣  Cadastros:"
echo "   - Menu Principal → Cadastros"
echo "   - Crie uma nova atração ou visitante"
echo ""
echo "=========================================="
echo ""
echo "📚 DOCUMENTAÇÃO"
echo ""
echo "  README.md                      → Visão geral do projeto"
echo "  FRONTEND_GUIDE.md              → Guia do frontend"
echo "  TESTING_GUIDE.md               → Procedimentos de teste"
echo "  IMPLEMENTATION_SUMMARY.md      → Resumo da implementação"
echo ""
echo "=========================================="
echo ""
echo "❓ DÚVIDAS?"
echo ""
echo "  ❌ Erro ao conectar com API?"
echo "     - Verifique se a API está rodando (Terminal 1)"
echo "     - Verifique se a porta 4567 está disponível"
echo ""
echo "  ❌ ID de visitante não encontrado?"
echo "     - Use um ID válido: 1, 2, 3, 4 ou 5"
echo ""
echo "  ❌ Porta 3000 já em uso?"
echo "     - Execute: npm run dev -- --port 3001"
echo ""
echo "=========================================="
echo ""
echo "✅ Tudo pronto! Comece agora!"
echo ""
